pipeline:
  identifier: Build_pushkarbhadang12_SeleniumTest_1704180207098
  name: Build SeleniumTest
  orgIdentifier: default
  projectIdentifier: SeleniumCucumberTest2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703314950386
        repoName: pushkarbhadang12/SeleniumTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Action
                  name: setup java
                  identifier: setup_java
                  spec:
                    uses: actions/setup-java@v3
                    with:
                      distribution: temurin
                      java-version: "17"
              - step:
                  type: Action
                  name: Setup Maven
                  identifier: setup_maven
                  spec:
                    uses: s4u/setup-maven-action@v1.7.0
                    with:
                      checkout-fetch-depth: 0
                      java-version: 17
                      java-distribution: temurin
                      maven-version: 3.9.6
              - step:
                  identifier: seleniumtest
                  name: seleniumtest
                  spec:
                    shell: Sh
                    command: mvn -B package --file RediffMoneyCucumberPOM/pom.xml
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
