pipeline:
  identifier: Build_pushkarbhadang12_SeleniumTest_1704180207098
  name: Build SeleniumTest
  orgIdentifier: default
  projectIdentifier: SeleniumCucumberTest2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703314950386
        repoName: pushkarbhadang12/SeleniumTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: seleniumtest
                  name: seleniumtest
                  spec:
                    shell: Sh
                    command: mvn -B package --file RediffMoneyCucumberPOM/pom.xml
                  timeout: ""
                  type: Run
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
